### ISSUE TITLE
Crash for duplicate entries in ExecutionState AddNewValue function

### ISSUE THREAD

**Issue by Siderale** [dotnet-security-guard/roslyn-security-guard#20]
A duplicate entry is added to the public IDictionary<string, VariableState> Variables when multiple errors with the same identifier are diagnosed. 

```
System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
       at RoslynSecurityGuard.Analyzers.Taint.ExecutionState.AddNewValue(String identifier, VariableState value) in C:\Users\Alexandre.Hains\Desktop\roslyn-security-guard-master\RoslynSecurityGuard\RoslynSecurityGuard\Analyzers\Taint\ExecutionState.cs:line 25
       at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitVariableDeclaration(VariableDeclarationSyntax declaration, ExecutionState state) [...]
```

**Comment by h3xstream** [comment]
@Siderale 
I am trying to reproduce the exception.

I have this : 
```csharp
public static void Run(string input)
{
    {
        string username = "ignore_me";
    }
    {
        string username = input;
        new SqlCommand("SELECT* FROM users WHERE username = '" + username + "' LIMIT 1");
    }
}
```

Is it also the case you added?

**Comment by h3xstream** [comment]
Instead of ignoring the new value. I would use it to override the value already in place. I am assuming is no longer available in this new context/block.

**Comment by Siderale** [comment]
Thanks for reopening the issue- I have this: 

SqlConnection connection = new SqlConnection("Data Source = (LocalDB)\\MSSQLLocalDB; AttachDbFilename = c:\\users\\...; Integrated Security = True;");

string query = "SELECT * FROM [User] WHERE user_id = 1";
SqlCommand cmd1 = new SqlCommand(query, connection);

query = String.Format("SELECT * FROM [User] WHERE user_id = ", 1);
SqlCommand cmd2 = new SqlCommand(query, connection)

In this situation, the second variable should be _Tainted_. Instead, as the first occurence is already marked as _Constant_, the second is considered _Constant_ as well.

I am currently trying a potential fix by using the GetReference() attribute of the Syntax nodes instead of the Identifier attribute. I will let you know.

**Comment by h3xstream** [comment]
The PR #24 is addressing this bug.
