### ISSUE TITLE
Object reference not set to an instance of an object in analysis

### ISSUE THREAD

**Issue by Mattacks** [dotnet-security-guard/roslyn-security-guard#30]
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An item with the same key has already been added.'.	blah		1	Active	Analyzer 'RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer' threw the following exception:

```
'Exception occurred with following context:
Compilation: blah
SyntaxTree: C:\blah.cs
SyntaxNode: public static System.Configuration ... [MethodDeclarationSyntax]@[13912..14863) (312,8)-(331,9)

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at RoslynSecurityGuard.Analyzers.Taint.ExecutionState.AddNewValue(String identifier, VariableState value)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitVariableDeclaration(VariableDeclarationSyntax declaration, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitLocalDeclaration(LocalDeclarationStatementSyntax declaration, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitStatement(SyntaxNode node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitStatement(SyntaxNode node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitStatement(SyntaxNode node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitStatement(SyntaxNode node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitStatement(SyntaxNode node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitStatement(SyntaxNode node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitMethodDeclaration(MethodDeclarationSyntax node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitMethods(SyntaxNodeAnalysisContext ctx)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	blah		1	Active	Analyzer 'RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: blah
SyntaxTree: C:\blah.cs
SyntaxNode: [System.Diagnostics.CodeAnalysis ... [MethodDeclarationSyntax]@[598..1342) (16,8)-(28,9)

System.NullReferenceException: Object reference not set to an instance of an object.
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitInvocationAndCreation(ExpressionSyntax node, ArgumentListSyntax argList, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitObjectCreation(ObjectCreationExpressionSyntax node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitExpression(ExpressionSyntax expression, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitAssignment(AssignmentExpressionSyntax node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitExpression(ExpressionSyntax expression, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitExpressionStatement(ExpressionStatementSyntax node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitStatement(SyntaxNode node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitMethodDeclaration(MethodDeclarationSyntax node, ExecutionState state)
   at RoslynSecurityGuard.Analyzers.Taint.TaintAnalyzer.VisitMethods(SyntaxNodeAnalysisContext ctx)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by h3xstream** [comment]
You can test this new release:
https://dotnet-security-guard.github.io/releases/RoslynSecurityGuard-2.1.0.vsix

**Comment by Mattacks** [comment]
Correlation is not causation I know, but seems to have gone away :-)

**Comment by xperiandri** [comment]
I have the same issue after I switched MVC 5 project to `project.json` to deal with dependency conflicts
